[package]
name = "yes"
version = "0.1.0"
authors = ["Daniele Olmisani <mad4j@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.3" }
